[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
harvverse = "HD1Bsrbw5tBKpLF3WE2gtnrDDYagNQgwHKAd9E3JZqst"

[programs.localnet]
harvverse = "HD1Bsrbw5tBKpLF3WE2gtnrDDYagNQgwHKAd9E3JZqst"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm test"

[hooks]
